name: Executar ETL no Jupyter

on:
  push:
    paths:
      - "dados/acao_petroleo2.csv"
  workflow_dispatch:

jobs:
  run_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install pandas openpyxl jupyter

      - name: Executar o ETL
        run: jupyter nbconvert --to notebook --execute petroleo.ipynb

      - name: Commit do arquivo processado
        run: |
          git config --global user.name "Juanpcsdev"
          git config --global user.email "juanpcsdev@gmail.com"
          git add dados/acao_petroleo2_clean.xlsx
          git commit -m "Novo arquivo processado pelo ETL"
          git push
