name: Run Notebook on CSV Commit

on:
  push:
    paths:
      - 'camada_ouro/Join_dataframes_new_end.csv'
      - 'camada_ouro/comparison_real_vs_preds_vs_erros_Dolar.csv'
      - 'camada_ouro/comparison_real_vs_preds_vs_erros_Real.csv'
      - 'camada_ouro/comparison_real_vs_preds_vs_erros_Petro.csv'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy papermill psycopg2-binary ipykernel

      - name: Run notebook with Papermill
        env:
          DB_USER: neondb_owner
          DB_PORT: 5432
          DB_PASSWORD: npg_W0GCygte8mLw
          DB_HOST: ep-gentle-fire-a8yuaaxi-pooler.eastus2.azure.neon.tech
          DB_NAME: neondb
          DB_SSL_MODE: require
        run: |
          papermill Notebooks/Database/database.ipynb Notebooks/Database/output.ipynb \
            -p DB_USER "$DB_USER" \
            -p DB_PASSWORD "$DB_PASSWORD" \
            -p DB_HOST "$DB_HOST" \
            -p DB_NAME "$DB_NAME" \
            -p DB_PORT "$DB_PORT" \
            -p DB_SSL_MODE "$DB_SSL_MODE"
