name: Run Notebook on CSV Commit

on:
  push:
    paths:
      - 'camada_ouro/Join_dataframes_new_end.csv'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy papermill psycopg2-binary

      - name: Run notebook with Papermill
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          papermill Notebooks/Database/database.ipynb Notebooks/Database/output.ipynb \
            -p DB_HOST "$DB_HOST" \
            -p DB_PORT "$DB_PORT" \
            -p DB_NAME "$DB_NAME" \
            -p DB_USER "$DB_USER" \
            -p DB_PASSWORD "$DB_PASSWORD"
